# Generated by Django 3.2.5 on 2021-08-28 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('Cash', '1'), ('Card to Card', '2'), ('Card Reader', '3')], default=1, max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('tax', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=755, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=755)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reciever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JewelryProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Geram', '1'), ('Methghal', '2')], default=1, max_length=55)),
                ('weight', models.FloatField()),
                ('number', models.IntegerField(default=0)),
                ('carat', models.CharField(choices=[('Carat18', '18'), ('Carat24', '24'), ('Carat750', '750')], default=18, max_length=55)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_images')),
                ('comment', models.CharField(blank=True, max_length=755, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoldProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Geram', '1'), ('Methghal', '2')], default=1, max_length=55)),
                ('weight', models.FloatField()),
                ('number', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_images')),
                ('comment', models.CharField(blank=True, max_length=755, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactorProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=225)),
                ('unit', models.CharField(choices=[('Geram', '1'), ('Methghal', '2')], default=1, max_length=55)),
                ('weight', models.FloatField(default=0.0)),
                ('product_type', models.CharField(choices=[('Gold', '1'), ('Coin', '2'), ('Jewlery', '3')], default=1, max_length=255)),
                ('price', models.CharField(default=0, max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=225)),
                ('factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_product', to='products.factor')),
            ],
        ),
        migrations.CreateModel(
            name='CoinProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('coin_type', models.CharField(choices=[('full', '1'), ('half', '2'), ('quarter', '1')], default=1, max_length=225)),
                ('unit', models.CharField(choices=[('Geram', '1'), ('Methghal', '2')], default=1, max_length=55)),
                ('weight', models.FloatField()),
                ('number', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=755, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
