# Generated by Django 3.2.5 on 2021-08-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='buyer_name',
            field=models.CharField(default='admin', max_length=225),
        ),
    ]
