# Generated by Django 3.2.5 on 2021-08-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_factor_buyer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='buyer_name',
            field=models.CharField(max_length=225),
        ),
    ]
