# Generated by Django 3.2.5 on 2021-08-30 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_factor_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinproduct',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
