# Generated by Django 3.2.5 on 2021-08-30 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20210830_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinProduct',
            new_name='Coin',
        ),
        migrations.RenameModel(
            old_name='GoldProduct',
            new_name='Gold',
        ),
        migrations.RenameModel(
            old_name='JewelryProduct',
            new_name='Jewelry',
        ),
    ]
