# Generated by Django 3.2.5 on 2021-08-30 17:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dashboardproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_images')),
                ('comment', models.CharField(blank=True, max_length=755, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DashBoardProduct',
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_type',
            field=models.CharField(choices=[('full', '1'), ('half', '2'), ('quarter', '3')], default=1, max_length=225),
        ),
    ]
