# Generated by Django 3.2.5 on 2021-09-08 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20210830_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('Gold', '1'), ('Coin', '2'), ('Jewlery', '3')], max_length=255)),
                ('info', models.CharField(max_length=755)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Geram', '1'), ('Methghal', '2')], default=1, max_length=55)),
                ('weight', models.FloatField()),
                ('number', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_images')),
                ('comment', models.CharField(blank=True, max_length=755, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='gold',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='seller',
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='Gold',
        ),
        migrations.DeleteModel(
            name='Jewelry',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='products.products'),
        ),
    ]
