# Generated by Django 3.2.5 on 2021-09-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210908_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='info',
            field=models.CharField(default='gold', max_length=755),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('Gold', '1'), ('Coin', '2'), ('Jewlery', '3')], default=1, max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
