# Generated by Django 3.2.5 on 2021-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210908_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
